### ISSUE TITLE
老哥，请务必忽视防火墙策略

### ISSUE THREAD

**Issue by gbaoye** [hubbylei/luci-app-clash#1]
拜托了！所有的插件都是基于忽视防火墙策略开发的

**Comment by hubbylei** [comment]
你在说啥0.0?

**Comment by gbaoye** [comment]
> 你在说啥0.0?

不要添加Lean固件的防火墙策略的解决方案

**Comment by hubbylei** [comment]
> > 你在说啥0.0?
> 
> 不要添加Lean固件的防火墙策略的解决方案

原作者就是这么写的。。。。我只是为了方便我自己用fork了一下，具体用的什么策略我还没研究过，抱歉:)

**Comment by gbaoye** [comment]
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53

**Comment by hubbylei** [comment]
> 

了解了

**Comment by hubbylei** [comment]
> iptables -t nat -A PRErouting -p udp --dport 53 -j REDIRECT --to-ports 53 iptables -t nat -A PRErouting -p tcp --dport 53 -j REDIRECT --to-ports 53 [ -n "$（command -v ip6tables）" ] && ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53 [ -n "$（command -v ip6tables）" ] && ip6tables -t nat -A PRErouting -p tcp --dport 53 -j REDIRECT --to-ports 53

了解了
